PYTHON = python3

install:
	$(PYTHON) -m pip install --upgrade pip
	$(PYTHON) -m pip install requests beautifulsoup4 pandas lxml html5lib selenium webdriver-manager

messi:
	$(PYTHON) messi.py

cristiano:
	$(PYTHON) cristiano.py

romario:
	$(PYTHON) romario.py

pele:
	$(PYTHON) pele.py

ronaldo:
	$(PYTHON) ronaldo.py

mbappe:
	$(PYTHON) mbappe.py

eusebio:
	$(PYTHON) eusebio.py

todos:
	$(PYTHON) messi.py
	$(PYTHON) cristiano.py
	$(PYTHON) romario.py
	$(PYTHON) pele.py
	$(PYTHON) ronaldo.py
	$(PYTHON) mbappe.py
	$(PYTHON) eusebio.py

freeze:
	$(PYTHON) -m pip freeze > requirements.txt

analise:
	$(PYTHON) analise.py